# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-23 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidLookup',
            fields=[
                ('pid', models.PositiveIntegerField(db_column='patient_id', primary_key=True, serialize=False)),
                ('mpid', models.PositiveIntegerField(db_column='nhsnum')),
                ('rid', models.CharField(db_column='brcid', max_length=255)),
                ('mrid', models.CharField(db_column='nhshash', max_length=255)),
                ('trid', models.PositiveIntegerField(db_column='trid')),
            ],
            options={
                'db_table': 'secret_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colour', models.PositiveSmallIntegerField(verbose_name='Colour number')),
                ('text', models.CharField(max_length=255, verbose_name='Text to highlight')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sql', models.TextField(verbose_name='SQL query')),
                ('args', picklefield.fields.PickledObjectField(editable=False, null=True, verbose_name='Pickled arguments')),
                ('raw', models.BooleanField(default=False, verbose_name='SQL is raw, not parameter-substituted')),
                ('qmark', models.BooleanField(default=True, verbose_name='Parameter-substituted SQL uses ?, not %s, as placeholders')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name="Deleted from the user's perspective. Audited queries are never properly deleted.")),
                ('audited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('count_only', models.BooleanField(default=False)),
                ('n_records', models.PositiveIntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('fail_msg', models.TextField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Query')),
            ],
        ),
    ]
