#!/usr/bin/env python
# Generated by Django 1.10.5 on 2017-02-16 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20170212_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='sql_hash',
            field=models.BigIntegerField(default=0, verbose_name='64-bit non-cryptographic hash of SQL query'),  # noqa
            preserve_default=False,
        ),
    ]
