# Generated by Django 2.1.2 on 2018-10-22 08:01

import cardinal_pythonlib.django.fields.jsonclassfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_patientexplorer_pmq_hash'),
    ]

    # noinspection PyPep8
    operations = [
        migrations.CreateModel(
            name='SitewideQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sql', models.TextField(verbose_name='SQL query')),
                ('sql_hash', models.BigIntegerField(verbose_name='64-bit non-cryptographic hash of SQL query')),
                ('args', cardinal_pythonlib.django.fields.jsonclassfield.JsonClassField(null=True, verbose_name='SQL arguments (as JSON)')),
                ('raw', models.BooleanField(default=False, verbose_name='SQL is raw, not parameter-substituted')),
                ('qmark', models.BooleanField(default=True, verbose_name='Parameter-substituted SQL uses ?, not %s, as placeholders')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name="Deleted from the user's perspective. Audited queries are never properly deleted.")),
                ('description', models.TextField(default='', verbose_name='query description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
