# Generated by Django 2.1.2 on 2018-12-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_query_display'),
    ]

    # noinspection PyPep8
    operations = [
        migrations.AddField(
            model_name='query',
            name='no_null',
            field=models.BooleanField(default=False, verbose_name='Omit Null columns for this query when displayed'),
        ),
    ]
