# Generated by Django 2.1.2 on 2018-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_query_no_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='last_run',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
