#!/usr/bin/env bash

# Run from .github/workflows/docs.yml
# Rebuild Sphinx docs from scratch and check generated files match those checked
# in

set -eux -o pipefail

sudo apt-get install texlive-latex-extra dvipng
python -m venv "${HOME}/venv"
source "${HOME}/venv/bin/activate"
python -VV
python -m site
python -m pip install -U pip
echo installing pip packages
python -m pip install -e .
python -m pip install mysqlclient
export CRATE_ANON_CONFIG=${HOME}/crate_anon_config.ini
export CRATE_WEB_LOCAL_SETTINGS=${HOME}/crateweb_local_settings.py
GATE_VERSION=9.0.1
wget -O "${HOME}/gate-installer.jar" https://github.com/GateNLP/gate-core/releases/download/v${GATE_VERSION}/gate-developer-${GATE_VERSION}-installer.jar
cd "${HOME}"
crate_nlp_write_gate_auto_install_xml --filename /tmp/gate_auto_install.xml --version $GATE_VERSION
java -jar "${HOME}/gate-installer.jar" "/tmp/gate_auto_install.xml"
export GATE_HOME=${HOME}/GATE_Developer_${GATE_VERSION}
crate_anon_demo_config > "${CRATE_ANON_CONFIG}"
cd "${GITHUB_WORKSPACE}/crate_anon/nlp_manager"
python ./build_gate_java_interface.py
crate_print_demo_crateweb_config > "${CRATE_WEB_LOCAL_SETTINGS}"
########################################################################################
cd "${GITHUB_WORKSPACE}/docs"
echo Creating autodocs
python ./create_all_autodocs.py --make --destroy_first
cd "${GITHUB_WORKSPACE}"
echo Checking if files generated by create_all_autodocs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
cd docs
echo Rebuilding docs
python ./rebuild_docs.py --skip_medex --warnings_as_errors
echo Checking if files generated by rebuild_docs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
