#!/usr/bin/env bash

# Run from .github/workflows/docs.yml
# Rebuild Sphinx docs from scratch and check generated files match those checked
# in

sudo apt-get install texlive-latex-extra dvipng
python -m venv "${HOME}/venv"
source "${HOME}/venv/bin/activate"
python -VV
python -m site
python -m pip install -U pip
echo installing pip packages
python -m pip install -e .
python -m pip install mysqlclient
crate_anon_web_create_private_settings
export CRATE_ANON_CONFIG=${HOME}/crate_anon_config.ini
export CRATE_WEB_LOCAL_SETTINGS=${HOME}/crateweb_local_settings.py
wget --progress=dot:giga -O "${HOME}/gate-installer.jar" https://github.com/GateNLP/gate-core/releases/download/v8.6.1/gate-developer-8.6.1-installer.jar
cd "${HOME}"
java -jar "${HOME}/gate-installer.jar" "${GITHUB_WORKSPACE}/docs/gate_auto_install.xml"
export GATE_HOME=${HOME}/GATE_Developer_8.6.1
crate_anon_demo_config > "${CRATE_ANON_CONFIG}"
cd "${GITHUB_WORKSPACE}/crate_anon/nlp_manager"
python ./build_gate_java_interface.py
crate_print_demo_crateweb_config > "${CRATE_WEB_LOCAL_SETTINGS}"
########################################################################################
cd "${GITHUB_WORKSPACE}/docs"
echo Creating autodocs
python ./create_all_autodocs.py --make --destroy_first
cd "${GITHUB_WORKSPACE}"
echo Checking if files generated by create_all_autodocs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
cd docs
echo Rebuilding docs
python ./rebuild_docs.py --skip_medex --warnings_as_errors
echo Checking if files generated by rebuild_docs need to be checked in
git diff
git update-index --refresh
git diff-index --quiet HEAD --
test -z "$(git ls-files --exclude-standard --others)"
