#!/usr/bin/env bash

set -e

echo installing pip packages
pip install .

echo checking packages for conflicts
pip check

echo installing safety checker
pip install safety

echo checking packages for vulnerabilities
# Ignore 39462 (CVE-2020-28476) (tornado <=6.1)
# https://github.com/tornadoweb/tornado/issues/2981
# It appears to be an issue with upstream python
safety check --full-report --ignore 39462

echo checking python for style and errors
flake8 --config=setup.cfg crate_anon

echo running tests
pytest -v
