# Generated by Django 2.1.2 on 2018-10-22 08:01

import crate_anon.crateweb.consent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0010_auto_20180629_1238'),
    ]

    # noinspection PyPep8
    operations = [
        migrations.AddField(
            model_name='study',
            name='summary_is_html',
            field=models.BooleanField(default=False, verbose_name='Is the summary in HTML (not plain text) format?'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(default=crate_anon.crateweb.consent.models._get_default_email_sender, max_length=255),
        ),
    ]
