# Generated by Django 2.1.2 on 2018-12-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0013_auto_20181223_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='rdbm_to_contact_pt',
            field=models.BooleanField(default=False),
        ),
    ]
