# Generated by Django 2.1.2 on 2019-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0014_contactrequest_rdbm_to_contact_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='clinician_signatory_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='clinician_signatory_title',
            field=models.TextField(default=None, null=True),
        ),
    ]
