# Generated by Django 2.1.5 on 2019-02-12 11:18

from cardinal_pythonlib.django.fields.restrictedcontentfile import (
    ContentTypeRestrictedFileField,
)
from django.db import migrations, models

from crate_anon.crateweb.consent.models import (
    leaflet_upload_to,
    study_details_upload_to,
    study_form_upload_to,
)
from crate_anon.crateweb.consent.storage import CustomFileSystemStorage

_DEFAULT_LOCATION = "C:/srv/crate/crate_filestorage"


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0015_auto_20190104_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(
                storage=CustomFileSystemStorage(
                    base_url="download_privatestorage",
                    location=_DEFAULT_LOCATION,
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="leaflet",
            name="pdf",
            field=ContentTypeRestrictedFileField(
                blank=True,
                storage=CustomFileSystemStorage(
                    base_url="download_privatestorage",
                    location=_DEFAULT_LOCATION,
                ),
                upload_to=leaflet_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="pdf",
            field=models.FileField(
                storage=CustomFileSystemStorage(
                    base_url="download_privatestorage",
                    location=_DEFAULT_LOCATION,
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="study_details_pdf",
            field=ContentTypeRestrictedFileField(
                blank=True,
                storage=CustomFileSystemStorage(
                    base_url="download_privatestorage",
                    location=_DEFAULT_LOCATION,
                ),
                upload_to=study_details_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="subject_form_template_pdf",
            field=ContentTypeRestrictedFileField(
                blank=True,
                storage=CustomFileSystemStorage(
                    base_url="download_privatestorage",
                    location=_DEFAULT_LOCATION,
                ),
                upload_to=study_form_upload_to,
            ),
        ),
    ]
