# Generated by Django 3.2.12 on 2022-02-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0016_auto_20190212_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummypatientsourceinfo",
            name="pt_discharged",
            field=models.BooleanField(
                null=True, verbose_name="Patient discharged"
            ),
        ),
        migrations.AlterField(
            model_name="patientlookup",
            name="pt_discharged",
            field=models.BooleanField(
                null=True, verbose_name="Patient discharged"
            ),
        ),
    ]
