# Generated by Django 4.2.21 on 2025-08-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "options",
                    models.ManyToManyField(to="nlp_classification.option"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_pk_value", models.CharField(max_length=100)),
                ("nlp_pk_value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TableDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_connection_name", models.CharField(max_length=100)),
                ("table_name", models.CharField(max_length=100)),
                ("pk_column_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp_classification.assignment",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nlp_classification.option",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp_classification.question",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp_classification.sourcerecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="nlp_table_definition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_records",
                to="nlp_classification.tabledefinition",
            ),
        ),
        migrations.AddField(
            model_name="sourcerecord",
            name="source_column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlp_classification.column",
            ),
        ),
        migrations.CreateModel(
            name="SampleSpec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("seed", models.PositiveIntegerField()),
                (
                    "nlp_table_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp_classification.tabledefinition",
                    ),
                ),
                (
                    "source_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlp_classification.column",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlp_classification.task",
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="table_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlp_classification.tabledefinition",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="sample_spec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlp_classification.samplespec",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="source_records",
            field=models.ManyToManyField(to="nlp_classification.sourcerecord"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlp_classification.task",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
