#!/usr/bin/env bash
# docker/linux/bash_within_docker
#
# Starts a container with the CRATE image and runs "bash" in it.

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
WITHIN_DOCKER="${THIS_DIR}/within_docker"

"${WITHIN_DOCKER}" /bin/bash
