#!/usr/bin/env bash
# server/docker/linux/camcops_server
#
# Launches the "crate_django_manage" command within one of the Docker
# containers running the CRATE image.

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
WITHIN_DOCKER="${THIS_DIR}/within_docker"

"${WITHIN_DOCKER}" /crate/venv/bin/crate_django_manage "$@"
# ^                ^                                   ^
# |                |                                   |
# |                |                                   |
# |                |                                   +- user arguments
# |                +- the crate_django_manage command
# +- execute within our Docker container...
