#!/usr/bin/env bash
# server/docker/linux/start_camcops_docker_interactive
#
# Launches the Docker Compose application in interactive mode.

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOCKER_COMPOSE_DIR="${THIS_DIR}/../dockerfiles"

# We must change directory to pick up ".env" etc.

cd "${DOCKER_COMPOSE_DIR}"

# Having done so, the default Docker Compose filenames include
# docker-compose.yaml, so we don't need to specify that.

# In interactive mode, it's also helpful if the containers abort on failure,
# rather than restarting (though restarting needs to be the default to cope
# with reboots in unattended mode). The "--abort-on-container-exit" option
# does this.

docker-compose up --abort-on-container-exit
