#!/usr/bin/env bash
# docker/linux/stop_crate_docker
#
# Takes down the Docker Compose application.

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOCKER_COMPOSE_DIR="${THIS_DIR}/../dockerfiles"

# We must change directory to pick up ".env" etc.

cd "${DOCKER_COMPOSE_DIR}"

# Having done so, the default Docker Compose filenames include
# docker-compose.yaml, so we don't need to specify that.

docker-compose down
